//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template, at 07/01/2016 15:36:19
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Dow.SSD.Framework.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;


namespace Dow.SSD.Framework.Repository
{
    public partial class tblTestRepository
    {
    		private SSDFrameworkSampleDBEntities _context = null;
    
    		public tblTestRepository(SSDFrameworkSampleDBEntities context)
    		{
    			_context = context;
    		}
    		
    		public bool Add(tblTest entity)
            {
    			_context.tblTests.Add(entity as tblTest);
    			return true;
            }
    		
    		public bool Add(List<tblTest> entities)
            {
                entities.ForEach(entity =>
                {
                    _context.tblTests.Add(entity as tblTest);
                });
    
    			return true;
            }
    
            public bool Update(tblTest entity)
            {
                _context.tblTests.Attach(entity as tblTest);
                _context.Entry(entity as tblTest).State = EntityState.Modified;
    
    			return true;
            }
    
            public bool Delete(tblTest entity)
            {
                _context.tblTests.Attach(entity as tblTest);
                _context.tblTests.Remove(entity as tblTest);
                  
               	return true;
            }
    
            public bool Delete(List<tblTest> entities)
            {
                entities.ForEach(entity =>
                {
                    _context.tblTests.Attach(entity as tblTest);
                    _context.tblTests.Remove(entity as tblTest);
                });
                return true;
            }
         
            public bool Delete(Expression<Func<tblTest, bool>> predicate)
            {
                var deleteEntity = this.FindAllBy(predicate);
    			this.FindAllBy(predicate).ToList().ForEach(entity =>
                {
                    _context.tblTests.Attach(entity as tblTest);
                    _context.tblTests.Remove(entity as tblTest);
                });
    
                return true;
            }
    
    		public tblTest FindSingleBy(Expression<Func<tblTest, bool>> predicate)
            {           
    		    _context.Configuration.ProxyCreationEnabled = false;
                var returnValue = _context.tblTests.Where(predicate).FirstOrDefault();
                return returnValue as tblTest;
            }
    
    		 public List<tblTest> FindAllBy(Expression<Func<tblTest, bool>> predicate)
            {
    		    _context.Configuration.ProxyCreationEnabled = false;
                return _context.tblTests.Where(predicate).ToList();
            }
         
            public List<tblTest> GetAll()
            {
    			_context.Configuration.ProxyCreationEnabled = false;
                var returnValue = _context.tblTests.ToList();
                return returnValue.Cast<tblTest>().ToList();
            }
    
    		public void SaveChanges()
    		{
    			_context.SaveChanges();
    		}
    		
    }
}
