

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template, at 07/01/2016 15:36:19
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Dow.SSD.Framework.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;


namespace Dow.SSD.Framework.Repository
{
}

